FROM openeuler/openeuler:23.09
LABEL maintainer="openEuler team, https://github.com/opensourceways"
RUN yum install -y ca-certificates git shadow wget xz tzdata
RUN mkdir -p /opt/soft/ && mkdir -p /opt/soft/node && mkdir -p /opt/etherpad-lite
RUN cd /opt/soft/ && wget https://nodejs.org/dist/v18.20.0/node-v18.20.0-linux-x64.tar.xz && tar -xf node-v18.20.0-linux-x64.tar.xz -C /opt/soft/node && rm -rf /opt/soft/node-v18.20.0-linux-x64.tar.xz
RUN ln -s /opt/soft/node/node-v18.20.0-linux-x64/bin/npm /usr/bin/npm && ln -s /opt/soft/node/node-v18.20.0-linux-x64/bin/node /usr/bin/node
RUN npm config set registry https://registry.npmmirror.com

ARG INSTALL_ABIWORD=
ARG INSTALL_SOFFICE=
ARG EP_HOME=
ARG EP_SHELL=
ARG EP_UID=5001
ARG EP_GID=0
ARG EP_DIR=/opt/etherpad-lite
ARG ETHERPAD_PLUGINS="ep_font_size ep_font_color ep_font_family ep_headings2 ep_themes ep_openid_connect ep_guest ep_user_displayname ep_stable_authorid"
RUN groupadd --system ${EP_GID:+--gid "${EP_GID}" --non-unique} etherpad && \
    useradd --system ${EP_UID:+--uid "${EP_UID}" --non-unique} --gid etherpad \
        ${EP_HOME:+--home-dir "${EP_HOME}"} --create-home \
        ${EP_SHELL:+--shell "${EP_SHELL}"} etherpad
RUN mkdir -p "${EP_DIR}" && chown etherpad:etherpad "${EP_DIR}"
RUN mkdir -p /usr/share/man/man1
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

USER etherpad
ENV NODE_ENV=production
ENV ETHERPAD_PRODUCTION=true
ENV TZ=Asia/Shanghai
WORKDIR "${EP_DIR}"

COPY --chown=etherpad:etherpad ./ ./
COPY --chown=etherpad:etherpad ./settings.json.docker "${EP_DIR}"/settings.json
RUN chmod +x /opt/etherpad-lite/src/bin/installDeps.sh && chmod +x /opt/etherpad-lite/src/bin/run.sh
RUN { [ -z "${ETHERPAD_PLUGINS}" ] || \
      npm install --no-save --legacy-peer-deps ${ETHERPAD_PLUGINS}; } && \
    src/bin/installDeps.sh && \
    rm -rf ~/.npm

RUN cp /opt/etherpad-lite/script/openid_client/client.js /opt/etherpad-lite/node_modules/openid-client/lib/client.js
RUN cp /opt/etherpad-lite/script/openid_client/helpers/request.js /opt/etherpad-lite/node_modules/openid-client/lib/helpers/request.js

RUN chmod -R g=u .

HEALTHCHECK --interval=20s --timeout=3s \
  CMD curl --silent http://localhost:9001/health | grep -E "pass|ok|up" > /dev/null || exit 1

EXPOSE 9001

CMD ["/opt/etherpad-lite/src/bin/run.sh"]
